# Generated by Django 4.1.2 on 2022-10-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'managed': False},
        ),
    ]
