# Generated by Django 4.1.2 on 2022-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'jobs_job',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
